
# Backend builder
FROM python:3.9-slim-buster as backend-builder
WORKDIR /app/backend
COPY backend/requirements.txt .
# COPY ../admin /app/admin 
RUN pip install --trusted-host pypi.python.org -r requirements.txt
COPY backend/ /app/backend/
ENV FLASK_APP=server.py
ENV FLASK_DEBUG=1
EXPOSE 5000
CMD ["python", "server.py"]

# Frontend builder
FROM node:19 as frontend-builder
WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ /app/frontend/

CMD ["npm", "run", "dev"]


