
# Backend builder
FROM python:3.9-slim-buster as backend-builder
WORKDIR /app
COPY requirements.txt .
# COPY ../admin /app/admin 
RUN pip install --trusted-host pypi.python.org -r requirements.txt
COPY . .
ENV FLASK_APP=server.py
ENV FLASK_DEBUG=1
EXPOSE 5000
CMD ["python", "server.py"]


